### PR TITLE
enable aarch64 and ppc64le

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Enable aarch64 on Drone and ppc64le on Travis (Defaults)

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@fhoehle The Travis CI check here (travis-ci.com) can be ignored (or turned off in settings I think?) The ppc64le build succeeds on travis-ci.org.

**Comment by FelixHoehleQC** [comment]
> ... (or turned off in settings I think?) ...
Unfortunately we can not, this bug is caused by travis.

**Comment by fhoehle** [comment]
> ... (or turned off in settings I think?) ...

@jayfurmanek Unfortunately we can not. This bug is caused by travis.
Thanks for adding the archs!

**Review by fhoehle — APPROVED** [review]

**Pull request merged**
